spring:
  application:
    name: space_x_service
  datasource:
    url: jdbc:sqlite:src/main/resources/db/space_x.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
